config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'publishers/new'

  get 'publishers/create'

  get 'publishers/update'

  get 'publishers/edit'

  get 'publishers/destroy'

  get 'publishers/index'

  get 'publishers/show'

  get 'authors/new'

  get 'authors/create'

  get 'authors/update'

  get 'authors/edit'

  get 'authors/destroy'

  get 'authors/index'

  get 'authors/show'

  get 'categories/new'

  get 'categories/create'

  get 'categories/update'

  get 'categories/edit'

  get 'categories/destroy'

  get 'categories/index'

  get 'categories/show'

  get 'books/new'

  get 'books/create'

  get 'books/update'

  get 'books/edit'

  get 'books/destroy'

  get 'books/index'

  get 'books/show'

  get 'about/index'

  get 'about' => 'about#index'

  get "/admin" => 'dashboard#index', :as => :admin

  root 'books#index'

  resources :books
  resources :authors
  resources :categories
  resources :publishers

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  
end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :books

	validates :first_name, presence: true
	validates :last_name, presence: true
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :category
	belongs_to :author
	belongs_to :publisher
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :books

	validates :name, presence: true,
				length: {minimum:3}
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
	has_many :books

	validates :name, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  	@page_title = 'About Us';
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @page_title = 'Add New Author'
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save  
      flash[:notice] = "Author Created"

      redirect_to authors_path
    else
      render 'new'
    end
  end

  def update
    @author = Author.find(params[:id])

    @author.update(author_params)

    flash[:notice] = 'Author Updated'

    redirect_to authors_path
  end

  def edit
    @author = Author.find(params[:id])
  end

  def destroy
    @author = Author.find(params[:id])

    @author.destroy

    flash[:notice] = 'Author Removed'

    redirect_to authors_path
  end

  def index
    @authors = Author.all
  end

  private
    def author_params
      params.require(:author).permit(:first_name, :last_name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  layout "main", except: [:show]

  def new
    @page_title = 'Add New Book'
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new
  end

  def create
    @book = Book.new(book_params)
    @book.save

    flash[:notice] = 'Book Added'

    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])

    @book.update(book_params)

    flash[:notice] = 'Book Updated'

    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])

    @book.destroy

    flash[:notice] = 'Book Removed'

    redirect_to books_path
  end

  def index
    @books = Book.all
    @categories = Category.all
  end

  def show
    @book = Book.find(params[:id])
    @categories = Category.all
  end

  private
    def book_params
    params.require(:book).permit(:title, :category_id, :author_id, :publisher_id, :isbn, :price, :buy, :format, :excerpt, :pages, :year, :coverpath)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @page_title = 'Add New Category'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save  
      flash[:notice] = "Category Created"

      redirect_to categories_path
    else
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:id])

    @category.update(category_params)

    flash[:notice] = 'Category Updated'

    redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])

    @category.destroy

    flash[:notice] = 'Category Removed'

    redirect_to categories_path
  end

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @books =  @category.books
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def new
    @page_title = 'Add New Publisher'
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher .save  
      flash[:notice] = "Publisher Created"

      redirect_to publishers_path
    else
      render 'new'
    end
  end

  def update
    @publisher = Publisher.find(params[:id])

    @publisher.update(publisher_params)

    flash[:notice] = 'Publisher Updated'

    redirect_to publishers_path
  end

  def edit
    @publisher = Publisher.find(params[:id])
  end

  def destroy
    @publisher = Publisher.find(params[:id])

    @publisher.destroy

    flash[:notice] = 'Publisher Removed'

    redirect_to publishers_path
  end

  def index
    @publishers = Publisher.all
  end

  private
    def publisher_params
      params.require(:publisher).permit(:name)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<h1><%= @page_title %></h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut rutrum felis, in egestas lacus. Sed convallis sagittis ligula, ac mollis dui posuere vitae. Sed id neque ornare, fermentum mauris pharetra, hendrerit sapien. Curabitur aliquam risus ipsum, vel bibendum ex luctus sagittis. Mauris elementum suscipit ante et egestas. Praesent sed leo elementum, faucibus est quis, euismod nunc. Duis pulvinar nisi non odio volutpat efficitur. Cras leo massa, ornare eu commodo mattis, placerat iaculis risus. Donec sed ligula sed felis elementum imperdiet a sit amet urna. Aliquam tempor, ex non luctus efficitur, augue sapien consequat ante, ut molestie dolor risus nec erat. Suspendisse faucibus odio vel felis vestibulum, ut bibendum dui sollicitudin. Integer dictum magna dui. Sed in libero iaculis, gravida augue et, consequat sem. Integer euismod semper ligula, at convallis ligula congue ullamcorper. Aenean at mollis quam, ut ornare enim.</p>

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h2>Edit Author</h2>

<%= form_for @author do |f| %>
	<!-- Check for errors -->
	<% if @author.errors.any? %>
	    <% @author.errors.full_messages.each do |msg| %>
	    	<!-- Show errors -->
	      	<div class="alert alert-danger"><%= msg %></div>
	    <% end %>
  	<% end %>

	<div class="form-group">
		<%= f.label :first_name %><br />
		<%= f.text_field :first_name, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :last_name %><br />
		<%= f.text_field :last_name, class:'form-control' %><br />
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%=link_to "Cancel", authors_path, class:'btn btn-default' %>

<% end %>

app/views/authors/index.html.erb
<h2>Authors</h2>

<table class="table table-striped">
	<tr>
		<th>Author Name</th>
		<th>Actions</th>
	</tr>

	<% @authors.each do |author| %>
		<tr>
			<td><%= author.first_name %> <%= author.last_name %></td>
			<td><%= link_to 'Edit', edit_author_path(author.id) %> | <%= link_to 'Delete', author_path(author), method: :delete, data: {confirm: 'Are you sure?'} %></td>
		</tr>
	<% end %>
</table>

app/views/authors/new.html.erb
<h2>Add New Author</h2>

<%= form_for @author do |f| %>
	<!-- Check for errors -->
	<% if @author.errors.any? %>
	    <% @author.errors.full_messages.each do |msg| %>
	    	<!-- Show errors -->
	      	<div class="alert alert-danger"><%= msg %></div>
	    <% end %>
  	<% end %>

	<div class="form-group">
		<%= f.label :first_name %><br />
		<%= f.text_field :first_name, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :last_name %><br />
		<%= f.text_field :last_name, class:'form-control' %><br />
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%=link_to "Cancel", authors_path, class:'btn btn-default' %>

<% end %>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h2>Edit Book</h2>

<%= form_for @book do |f| %>

	<div class="form-group">
		<%= f.label :title %><br />
		<%= f.text_field :title, class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :isbn %><br />
		<%= f.text_field :isbn ,class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :category %><br />
		<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'},class:'form-control' %><br /><br />
	</div>

	<div class="form-group">
		<%= f.label :author %><br />
		<%= f.select :author_id, Author.all.collect {|x| [x.first_name + ' '+ x.last_name, x.id]}, {:include_blank => 'Select One'},class:'form-control' %><br /><br />
	</div>

	<div class="form-group">
		<%= f.label :publisher %><br />
		<%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'},class:'form-control' %><br /><br />
	</div>

	<div class="form-group">
		<%= f.label :format %><br />
		<%= f.text_field :format ,class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :year %><br />
		<%= f.text_field :year ,class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :coverpath %><br />
		<%= f.text_field :coverpath ,class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :excerpt %><br />
		<%= f.text_area :excerpt ,class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :pages %><br />
		<%= f.number_field :pages ,class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :price %><br />
		<%= f.text_field :price ,class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :buy %><br />
		<%= f.text_field :buy ,class:'form-control' %><br />
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%=link_to "Cancel", books_path, class:'btn btn-default' %>

<% end %>

app/views/books/index.html.erb
<div id="books-index">
	<% @books.each_slice(4) do |book| %>
		<div class="row">
			<% book.each do |book| %>
				<div class="col-md-3 col-sm-3">
				<h3><%= book.title %></h3>
				<%= image_tag(book.coverpath) %>
				<%= link_to 'Read More', book_path(book), class:'btn btn-primary' %>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

app/views/books/new.html.erb
<h2>Add New Book</h2>

<%= form_for @book do |f| %>

	<div class="form-group">
		<%= f.label :title %><br />
		<%= f.text_field :title, class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :isbn %><br />
		<%= f.text_field :isbn ,class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :category %><br />
		<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'},class:'form-control' %><br /><br />
	</div>

	<div class="form-group">
		<%= f.label :author %><br />
		<%= f.select :author_id, Author.all.collect {|x| [x.first_name + ' '+ x.last_name, x.id]}, {:include_blank => 'Select One'},class:'form-control' %><br /><br />
	</div>

	<div class="form-group">
		<%= f.label :publisher %><br />
		<%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'},class:'form-control' %><br /><br />
	</div>

	<div class="form-group">
		<%= f.label :format %><br />
		<%= f.text_field :format ,class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :year %><br />
		<%= f.text_field :year ,class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :coverpath %><br />
		<%= f.text_field :coverpath ,class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :excerpt %><br />
		<%= f.text_area :excerpt ,class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :pages %><br />
		<%= f.number_field :pages ,class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :price %><br />
		<%= f.text_field :price ,class:'form-control' %><br />
	</div>

	<div class="form-group">
		<%= f.label :buy %><br />
		<%= f.text_field :buy ,class:'form-control' %><br />
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%=link_to "Cancel", books_path, class:'btn btn-default' %>

<% end %>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/index.html.erb
<h2>Categories</h2>

<table class="table table-striped">
	<tr>
		<th>Category Name</th>
		<th>Actions</th>
	</tr>

	<% @categories.each do |category| %>
		<tr>
			<td><%= category.name %></td>
			<td><%= link_to 'Edit', edit_category_path(category.id) %> | <%= link_to 'Delete', category_path(category), method: :delete, data: {confirm: 'Are you sure?'} %></td>
		</tr>
	<% end %>
</table>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>
<div id="books-index">
	<% @books.each_slice(4) do |book| %>
		<div class="row">
			<% book.each do |book| %>
				<div class="col-md-3 col-sm-3">
				<h3><%= book.title %></h3>
				<%= image_tag(book.coverpath) %>
				<%= link_to 'Read More', book_path(book), class:'btn btn-primary' %>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title ? @page_title : 'Welcome' %> | The BookStore</title>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:controller] == 'books' ? 'active' : '' %>"><%= link_to 'Home', root_path %></li>          
          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </div>

    <header>
    	<div class="container">
    		<h1>mojBookStore</small></h1>
    	</div>
    </header>

    <section>
    	<div class="container">
    		<div class="row">
    			<div class="col-md-8">
            <!-- Alerts & Messages -->
          <% if flash[:notice] %>
            <div class="alert alert-success"><%= flash[:notice] %></div>
          <% end %>

          <% if flash[:alert] %>
            <div class="alert alert-danger"><%= flash[:alert] %></div>
          <% end %>
					<%= yield %>
				</div>
				<div class="col-md-4">
					<%= render 'partials/sidebar' %>
				</div>
			</div>
		</div>
	</section>

	<footer>
		<div class="container">
			<p>Copyright &copy; 2015, All Rights Reserved | <%= link_to "Admin", admin_path %></p>
		</div>
	</footer>

</body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= @page_title ? @page_title : 'Welcome' %> | The BookStore</title>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application','style','swipebox', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application','jquery.swipebox.min','jquery-1.11.1.min','bootstrap.js','easing','main','modernizr', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900,200italic,300italic,400italic,600italic,700italic,900italic' rel='stylesheet' type='text/css'>


<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } 
</script>

<script type="text/javascript">
	jQuery(document).ready(function($) {
		$(".scroll").click(function(event){		
			event.preventDefault();
			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
		});
	});
</script>

</head>
<body>

	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><h2 style="padding-top: 8px; font-weight: bold; font-family:Georgia; ">mojBookStore</h2></li>         
          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </div>

	<div class="banner">
		<div class="container">
			<div class="header">
				<div class="logo">
					<%= image_tag("logo.png") %>
				</div>
				<div class="logo-right">
						<nav class="cl-effect-1">
							<ul class="nav1">
								<li><%= image_tag("menu.png") %></li>
								<li><a href="#portfolio" class="scroll">Books</a></li>
								<li><a href="#about" class="scroll">About</a></li>
								<li><a href="#contact" class="scroll">Contact Us</a></li>
							</ul>
						</nav>
				</div>
				<div class="clearfix"> </div>
			</div>
			<!-- script for menu -->
					<script> 
						$( "span.menu" ).click(function() {
						$( "ul.nav1" ).slideToggle( 300, function() {
						 // Animation complete.
						});
						});
					</script>
				<!-- //script for menu -->
			<div class="banner-info">
				<h1>Where Your Programming Begins</h1>
				<p>...also Where Your Life ends...</p>
				<div class="read">
					<%= link_to "More About Us", about_path, class:'hvr-rectangle-out' %>
				</div>
			</div>
		</div>
	</div>
<!-- //banner -->
<!-- portfolio -->
	<!--<div id="portfolio" class="portfolio">
	<h2>Books</h2>

		<section>
    	<div class="container">
    		<div class="row">
    			<div class="col-md-8">

          <% if flash[:notice] %>
            <div class="alert alert-success"><%= flash[:notice] %></div>
          <% end %>

          <% if flash[:alert] %>
            <div class="alert alert-danger"><%= flash[:alert] %></div>
          <% end %>
					<%= yield %>
				</div>
				<div class="col-md-4">
					<%= render 'partials/sidebar' %>
				</div>
			</div>
		</div>
	</section>
	</div> -->


	<div id="portfolio" class="portfolio">
		<div class="container">
			<h2>Book Categories</h2>
			<div class="portfolio-grids">
				<div class="col-md-6 portfolio-grid">	
					<div class="portfolio-grid1">
					<a href="categories/1" class="b-link-stripe b-animate-go"  title="">
						<%= image_tag("1.jpg")%>
						<div class="b-wrapper">
							<h2 class="b-animate b-from-left    b-delay03 ">
								<div class="text-info">
									<h4>Ruby On Rails</h4>
								</div>
							</h2>
						</div>
					</a>
					</div>
					<div class="portfolio-grid1">
					<a href="categories/4" class="b-link-stripe b-animate-go"  title="">
						<%= image_tag("4.jpg")%>
						<div class="b-wrapper">
							<h2 class="b-animate b-from-left    b-delay03 ">
								<div class="text-info text-info1">
									<h4>AJAX</h4>
								</div>
							</h2>
						</div>
					</a>
					</div>
				</div>
				<div class="col-md-6 portfolio-grid">
					<div class="portfolio-grid1">
					<a href="categories/2" class="b-link-stripe b-animate-go"  title="">
						<%= image_tag("2.png")%>
						<div class="b-wrapper">
							<h2 class="b-animate b-from-left    b-delay03 ">
								<div class="text-info text-info1 Forest">
									<h4>PHP</h4>
								</div>
							</h2>
						</div>
					</a>
					</div>
					<div class="portfolio-grid1">
					<a href="categories/3" class="b-link-stripe b-animate-go"  title="">
						<%= image_tag("3.png")%>
						<div class="b-wrapper">
							<h2 class="b-animate b-from-left    b-delay03 ">
								<div class="text-info asd">
									<h4>HTML5</h4>
								</div>
							</h2>
						</div>
					</a>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>


		<script type="text/javascript">
			jQuery(function($) {
				$(".swipebox").swipebox();
			});
		</script>
<!-- //portfolio -->
<!-- about -->
	<div id="about" class="about">
		<div class="container">
			<div class="about-info">
				<h3>About Us</span></h3>
				<p><p style="color:white;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut rutrum felis, in egestas lacus. Sed convallis sagittis ligula, ac mollis dui posuere vitae. Sed id neque ornare, fermentum mauris pharetra, hendrerit sapien. Curabitur aliquam risus ipsum, vel bibendum ex luctus sagittis. Mauris elementum suscipit ante et egestas. Praesent sed leo elementum, faucibus est quis, euismod nunc. Duis pulvinar nisi non odio volutpat efficitur.</p></p>
				<div class="read1">
					<%= link_to "Location info", about_path, class:'hvr-rectangle-out' %>
				</div>
			</div>
		</div>
	</div>
<!-- //about -->
<!-- contact -->
	<div class="contact" id="contact">
		<div class="container">
			<h2>Contact Us</h2>
			<div class="contact-info">
				<ul>
					<li class="first">
						<div class="position">
							<a href="#" class=" icon user"></a><input type="text" class="text" value="Enter Name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter Name';}">
							<div class="clear"></div>
							<div class="dot">
								<span> </span>
							</div>
						</div>
					</li>
					<li class="first">
						<div class="position">
							<a href="#" class=" icon email"></a><input type="text" class="text" value="Enter email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter email';}">
							<div class="clear"></div>
							<div class="dot">
								<span> </span>
							</div>
						</div>
					</li>
					<div class="clearfix"> </div>
					<li class="second">
						<div class="position">
							<a href="#" class=" icon msg"></a><textarea value="Enter message" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Comments';}">Enter message</textarea>
							<div class="clear"></div>
							<div class="dot1">
								<span> </span>
							</div>
						</div>
					</li>
				</ul>
				<input type="submit" onclick="myFunction()" value="SEND">
			</div>
		</div>
	</div>
<!-- //contact -->

<!-- footer -->
	<footer>
		<div class="container">
			<p>Copyright &copy; 2015, All Rights Reserved | <%= link_to "Admin", admin_path %></p>
		</div>
	</footer>
<!-- //footer -->
<!-- here stars scrolling icon -->
		<a href="#0" class="cd-top">Top</a>
<!-- //here ends scrolling icon -->
</body>
</html>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'about' %>
	<div class="well">
		<h3>Location Info</h3>
		<ul>
			<li>mojBookStore</li>
			<li>Neka Ulica 3</li>
			<li>Zagreb, 10090</li>
			<li>Phone: (+385) 01/5555-555</li>
			<li>Email: mojemail@gmail.com</li>
		</ul>
	</div>
<% end %>
<% if params[:controller] == 'books' && params[:action] == 'index' || params[:action] == 'show' %>
	<div class="list-group">
		<% @categories.each do |category| %>
			<%= link_to category.name, category_path(category.id), class:'list-group-item' %>
		<% end %>
	</div>
<% end %>

app/views/publishers/index.html.erb
<h2>Publishers</h2>

<table class="table table-striped">
	<tr>
		<th>Publisher Name</th>
		<th>Actions</th>
	</tr>

	<% @publishers.each do |publisher| %>
		<tr>
			<td><%= publisher.name %></td>
			<td><%= link_to 'Edit', edit_publisher_path(publisher.id) %> | <%= link_to 'Delete', publisher_path(publisher), method: :delete, data: {confirm: 'Are you sure?'} %></td>
		</tr>
	<% end %>
</table>